permalink: /:categories/:title.html
auto: true
pygments: true
exclude: ["Rakefile", "README.md", "CNAME"]
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
production_url : http://jekyllbootstrap.com
title : My Blog =)
author :
  name : Jade Dominguez
  email : plusjade@gmail.com
  github : plusjade
  twitter : plusjade